name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: automationcloud/chrome:c86-node14
      env:
        CHROME_PATH: /opt/latest/chrome
        CHROME_PORT: "9123"
        CHROME_HEADLESS: "true"
        REDIS_HOST: redis
        MONGO_URL: mongodb://mongodb:27017/
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mongodb:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Exclude Autopilot
        run: rm -rf packages/autopilot && sed /autopilot/d tsconfig.json > temp && mv temp tsconfig.json
      - run: npm run ci:bootstrap
      - run: npm run compile
      - run: npm run lint
      - run: npm test
